Update to python ^3 and Django ^3 & remove support for older versions
andersinno/django-form-designer-ai pull request #41
Opened 2022-06-15 15:20 UTC by wiltso

2022-06-15 18:22 UTC, akx commented
FWIW, you may find some of this work done in https://github.com/kcsry/django-form-designer already...

2022-06-16 04:47 UTC, suutari-ai commented
I think we should either use the kcsry's version directly or if it doesn't have all of the needed fixen, then it would be better to contribute them there. AFAIK that's the most well maintained fork of django-form-designer atm.

2022-06-16 05:04 UTC, akx commented
Well, we have removed Django-CMS support in that fork, which I would imagine you need 😅

2022-06-16 08:13 UTC, suutari-ai commented
Oh, OK. Then we might still need to maintain our own fork after all. :cry:

2022-06-16 08:29 UTC, Niilis requested changes
Nice to get standardized coding practices into use.

I spotted one very old check that could be removed. Also, the main README has some old claims that this commit makes faulty. It should be updated to state that this will be compatible with Django >3.

2022-06-16 08:29 UTC, Niilis commented on form_designer/email.py
>      if DJANGO_18:  # the reply_to kwarg is only supported in Django 1.8+ . . .
This check seems awfully outdated.

It should be OK to remove the if check here and the fallback a few lines down.

2022-06-17 08:41 UTC, Niilis approved these changes
I think this is good to go! :shipit:

2022-06-28 05:45 UTC, merged